// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from "contentful";
import { Document } from "@contentful/rich-text-types";

export interface IAccordionFields {
  /** Internal Name */
  name?: string | undefined;

  /** Theme */
  theme?: "dark" | "light" | undefined;

  /** Headline */
  headline?: IHeadline | undefined;

  /** Section ID */
  sectionId?: string | undefined;

  /** Items */
  items?: IAccordionItem[] | undefined;
}

export interface IAccordion extends Entry<IAccordionFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "accordion";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IAccordionItemFields {
  /** Internal Name */
  internalName?: string | undefined;

  /** Media */
  media?: IImage | undefined;

  /** Content */
  content?: IText | undefined;
}

/** Specific to Module - Accordion */

export interface IAccordionItem extends Entry<IAccordionItemFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "accordionItem";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ICardFields {
  /** Internal Name */
  name?: string | undefined;

  /** Eyebrow */
  eyebrow?: string | undefined;

  /** Title */
  title: string;

  /** Body */
  body: Document;

  /** Image */
  image: IImage;

  /** Call to Action */
  cta?: ILink[] | undefined;

  /** Variant */
  variant?: "vertical" | "horizontal" | undefined;
}

export interface ICard extends Entry<ICardFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "card";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ICareersListFields {
  /** Internal Name */
  name?: string | undefined;

  /** Theme */
  theme?: "dark" | "light" | undefined;

  /** Headline */
  headline?: IHeadline | undefined;

  /** Section ID */
  sectionId?: string | undefined;

  /** Department Filter */
  department?: string | undefined;

  /** Location Filter */
  location?: string | undefined;

  /** Hide Filters? */
  hideFilters?: boolean | undefined;
}

export interface ICareersList extends Entry<ICareersListFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "careersList";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IComparisonTableFields {
  /** Internal Name */
  internalName?: string | undefined;

  /** Theme */
  theme?: "dark" | "light" | undefined;

  /** Headline */
  headline?: IHeadline | undefined;

  /** Section ID */
  sectionId?: string | undefined;

  /** Table */
  table?: Document | undefined;
}

export interface IComparisonTable extends Entry<IComparisonTableFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "comparisonTable";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ICtaBannerFields {
  /** Internal Name */
  name?: string | undefined;

  /** Theme */
  theme?: "dark" | "light" | undefined;

  /** Eyebrow */
  eyebrow?: string | undefined;

  /** Title */
  title: string;

  /** In Page Nav Title */
  inPageNavTitle?: string | undefined;

  /** Section ID */
  sectionId?: string | undefined;

  /** Subhead */
  subhead?: string | undefined;

  /** Body */
  body?: Document | undefined;

  /** Alignment */
  alignment?: "left" | "center" | "right" | undefined;

  /** Call to Action */
  cta?: ILink[] | undefined;
}

export interface ICtaBanner extends Entry<ICtaBannerFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "ctaBanner";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IDividerFields {
  /** Internal Name */
  internalName?: string | undefined;

  /** Theme */
  theme?: "dark" | "light" | undefined;
}

/** A horizontal line to divide up content and sections */

export interface IDivider extends Entry<IDividerFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "divider";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IFeatureFields {
  /** Internal Name */
  name?: string | undefined;

  /** Theme */
  theme?: "dark" | "light" | undefined;

  /** Eyebrow */
  eyebrow?: string | undefined;

  /** Title */
  title?: string | undefined;

  /** In Page Nav Title */
  inPageNavTitle?: string | undefined;

  /** Section ID */
  sectionId?: string | undefined;

  /** Subhead */
  subhead?: string | undefined;

  /** Body */
  body?: Document | undefined;

  /** Vertical Alignment */
  textAlignment?: "Top" | "Bottom" | undefined;

  /** Media */
  media?: IImage | undefined;

  /** Vimeo Id */
  vimeoId?: string | undefined;

  /** Vimeo Button Text */
  vimeoBtnText?: string | undefined;

  /** Media Side */
  mediaSide?: "Left" | "Right" | undefined;

  /** Media Fixed Size */
  mediaFixedSize?: boolean | undefined;

  /** Call to Action */
  cta?: ILink[] | undefined;
}

export interface IFeature extends Entry<IFeatureFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "feature";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IFeatureStackFields {
  /** Internal Name */
  name?: string | undefined;

  /** Theme */
  theme?: "light" | "dark" | undefined;

  /** Eyebrow */
  eyebrow?: string | undefined;

  /** Title */
  title?: string | undefined;

  /** Section Id */
  sectionId?: string | undefined;

  /** In Page Nav Title */
  inPageNavTitle?: string | undefined;

  /** Body */
  body?: Document | undefined;

  /** Features */
  features: IFeature[];
}

/** Display one or more Feature modules in a stacked list */

export interface IFeatureStack extends Entry<IFeatureStackFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "featureStack";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IFootnoteFields {
  /** Internal title */
  internalTitle?: string | undefined;

  /** Reference */
  reference?: string | undefined;

  /** Text */
  text: string;

  /** Note */
  note?: string | undefined;
}

export interface IFootnote extends Entry<IFootnoteFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "footnote";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IFormFields {
  /** Internal Name */
  name?: string | undefined;
}

export interface IForm extends Entry<IFormFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "form";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IHeadlineFields {
  /** Internal name */
  internalName?: string | undefined;

  /** Eyebrow */
  eyebrow?: string | undefined;

  /** Title */
  title: string;

  /** In Page Nav Title */
  inPageNavTitle?: string | undefined;

  /** Section ID */
  sectionId?: string | undefined;

  /** Subhead */
  subhead?: string | undefined;

  /** Body */
  body?: Document | undefined;

  /** Alignment */
  alignment?: "left" | "center" | undefined;

  /** Call to Action */
  cta?: ILink[] | undefined;
}

export interface IHeadline extends Entry<IHeadlineFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "headline";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IHeroFields {
  /** Internal Name */
  name?: string | undefined;

  /** Theme */
  theme?: "dark" | "light" | undefined;

  /** Eyebrow */
  eyebrow?: string | undefined;

  /** Title */
  title: string;

  /** In Page Nav Title */
  inPageNavTitle?: string | undefined;

  /** Section ID */
  sectionId?: string | undefined;

  /** Subhead */
  subhead?: string | undefined;

  /** Body */
  body: Document;

  /** Background */
  background: IImage;

  /** Call to Action */
  cta?: ILink[] | undefined;

  /** Height */
  height?: "browser" | "content" | "media" | undefined;
}

export interface IHero extends Entry<IHeroFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "hero";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IHeroCarouselFields {
  /** Internal Name */
  name?: string | undefined;
}

export interface IHeroCarousel extends Entry<IHeroCarouselFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "heroCarousel";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IIconFields {
  /** Internal Name */
  name?: string | undefined;

  /** SVG */
  svg?: string | undefined;
}

/** Takes an SVG as an icon. Generally used for Icon libraries. */

export interface IIcon extends Entry<IIconFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "icon";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IImageFields {
  /** Internal Name */
  name?: string | undefined;

  /** Image/Video */
  image: Asset;

  /** Image/Video - mobile */
  mobileImage?: Asset | undefined;

  /** Ratio */
  ratio?: "auto" | "16-9" | "4-5" | "1-1" | undefined;
}

/** Used to display an image or a background video loop. */

export interface IImage extends Entry<IImageFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "image";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IInPageNavFields {
  /** Internal Title */
  internalTitle?: string | undefined;

  /** Theme */
  theme?: "light" | "dark" | undefined;

  /** Title */
  title?: string | undefined;

  /** Section Id */
  sectionId?: string | undefined;

  /** Section Links */
  sectionLinks: (
    | IAccordion
    | ICareersList
    | IComparisonTable
    | ICtaBanner
    | IFeature
    | IFeatureStack
    | IHeadline
    | IHero
    | IList
    | ILogoCloud
    | IMarketoForm
    | IMulticard
    | IPanorama
    | IPostList
    | IQuote
    | IText
    | IVideo
  )[];
}

/** This is a module that links to sections within a page via the section's id. */

export interface IInPageNav extends Entry<IInPageNavFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "inPageNav";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ILinkFields {
  /** Internal Name */
  name?: string | undefined;

  /** Label */
  text: string;

  /** Page */
  page?: IPage | IPageSimple | IPost | undefined;

  /** URL */
  url?: string | undefined;

  /** New Window */
  newWindow?: boolean | undefined;
}

/** Call to Action */

export interface ILink extends Entry<ILinkFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "link";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IListFields {
  /** Internal Name */
  name?: string | undefined;

  /** Theme */
  theme?: "dark" | "light" | undefined;

  /** Headline */
  headline?: IHeadline | undefined;

  /** Section ID */
  sectionId?: string | undefined;

  /** Items */
  items?: IListItem[] | undefined;

  /** Variant */
  variant?: "One column" | "Two columns" | undefined;

  /** Display bullet list number? */
  showIndex?: boolean | undefined;
}

export interface IList extends Entry<IListFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "list";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IListItemFields {
  /** Internal Name */
  name?: string | undefined;

  /** Title */
  title: string;

  /** Body */
  body?: Document | undefined;

  /** Call to Action */
  link?: ILink | undefined;
}

/** Used in the module - List */

export interface IListItem extends Entry<IListItemFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "listItem";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ILogoCloudFields {
  /** Internal Name */
  name?: string | undefined;

  /** Theme */
  theme?: "auto" | "light" | "dark" | undefined;

  /** Headline */
  headline?: IHeadline | undefined;

  /** Section ID */
  sectionId?: string | undefined;

  /** Images */
  images: Asset[];
}

export interface ILogoCloud extends Entry<ILogoCloudFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "logoCloud";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IMarketoFormFields {
  /** Internal Name */
  internalName: string;

  /** Theme */
  theme?: "dark" | "light" | undefined;

  /** Headline */
  headline?: IHeadline | undefined;

  /** Section ID */
  sectionId?: string | undefined;

  /** Form ID */
  formId: string;
}

export interface IMarketoForm extends Entry<IMarketoFormFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "marketoForm";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IMulticardFields {
  /** Internal Name */
  name?: string | undefined;

  /** Theme */
  theme?: "dark" | "light" | undefined;

  /** Headline */
  headline?: IHeadline | undefined;

  /** Section ID */
  sectionId?: string | undefined;

  /** Cards */
  multicardItems: ICard[];

  /** Variant */
  variant?: "column" | "grid" | "carousel" | undefined;
}

export interface IMulticard extends Entry<IMulticardFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "multicard";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface INavItemFields {
  /** Internal Name */
  name?: string | undefined;

  /** Title */
  title?: string | undefined;

  /** Subnav Lists */
  subnavLists?: ISimpleList[] | undefined;

  /** Nav Feature */
  navFeature?: (ICard | IPostList)[] | undefined;

  /** Nav Feature Background Color */
  navFeatureBg?: "yellow" | "green" | "gray" | "black" | undefined;
}

/** Specific to navigation */

export interface INavItem extends Entry<INavItemFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "navItem";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IPageFields {
  /** Theme */
  theme?: "dark" | "light" | undefined;

  /** Title */
  title: string;

  /** Slug */
  slug: string;

  /** Sections */
  sections?:
    | (
        | ISection
        | IAccordion
        | ICareersList
        | IFeature
        | IHero
        | IList
        | ILogoCloud
        | IMulticard
        | IPanorama
        | IPostList
        | IQuote
        | IText
        | IHeadline
        | ICtaBanner
        | IFeatureStack
        | IDivider
        | IVideo
        | IComparisonTable
        | IInPageNav
      )[]
    | undefined;

  /** Metadata */
  metadata?: ISeo | undefined;

  /** Display this translation? */
  translated?: boolean | undefined;
}

export interface IPage extends Entry<IPageFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "page";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IPageSimpleFields {
  /** Title */
  title: string;

  /** Slug */
  slug: string;

  /** Text */
  text?: Document | undefined;

  /** Metadata */
  metadata?: ISeo | undefined;

  /** Display this translation? */
  translated?: boolean | undefined;
}

export interface IPageSimple extends Entry<IPageSimpleFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "pageSimple";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IPanoramaFields {
  /** Internal Name */
  name?: string | undefined;

  /** Theme */
  theme?: "dark" | "light" | undefined;

  /** Headline */
  headline?: IHeadline | undefined;

  /** Section ID */
  sectionId?: string | undefined;

  /** Images */
  images: Asset[];

  /** Ratio */
  ratio?: "auto" | "1-1" | "4-5" | "16-9" | undefined;
}

export interface IPanorama extends Entry<IPanoramaFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "panorama";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IPersonFields {
  /** Name */
  name: string;

  /** Title */
  title?: string | undefined;

  /** Bio */
  bio?: string | undefined;

  /** Photo */
  photo?: Asset | undefined;

  /** Twitter Username */
  twitter?: string | undefined;

  /** LinkedIn Username */
  linkedIn?: string | undefined;

  /** Facebook Username */
  facebook?: string | undefined;

  /** Business Groups */
  businessGroups?: "Design" | "Engineering" | "Marketing" | undefined;
}

export interface IPerson extends Entry<IPersonFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "person";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IPostFields {
  /** Theme */
  theme?: "light" | "dark" | undefined;

  /** Title */
  title: string;

  /** Type */
  type?: "blog" | undefined;

  /** Category */
  category?: "Design" | "Engineering" | "Work" | undefined;

  /** Slug */
  slug: string;

  /** Eyebrow */
  eyebrow?: string | undefined;

  /** Subhead */
  subhead?: string | undefined;

  /** Subhead Description */
  subheadDescription?: string | undefined;

  /** Text */
  text: Document;

  /** Thumbnail Text */
  thumbnailText?: string | undefined;

  /** Author */
  author?: IPerson | undefined;

  /** Published On */
  publishedOn?: string | undefined;

  /** Hero Image */
  heroImage?: Asset | undefined;

  /** Thumbnail Image */
  thumbnailImage?: Asset | undefined;

  /** ctaBanner */
  ctaBanner?: ICtaBanner[] | undefined;

  /** Metadata */
  metadata?: ISeo | undefined;

  /** Show Table of Contents */
  toc?: boolean | undefined;

  /** Display this translation? */
  translated?: boolean | undefined;
}

export interface IPost extends Entry<IPostFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "post";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IPostListFields {
  /** Internal Name */
  name?: string | undefined;

  /** Theme */
  theme?: "dark" | "light" | undefined;

  /** Headline */
  headline?: IHeadline | undefined;

  /** Section ID */
  sectionId?: string | undefined;

  /** Sort */
  sort?: "title" | "publishedOn" | undefined;

  /** Order */
  order?: "asc" | "desc" | undefined;

  /** Limit */
  limit?: number | undefined;
}

export interface IPostList extends Entry<IPostListFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "postList";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IPostListingSettingsFields {
  /** Internal Name */
  internalName: string;

  /** Hero Title */
  heroTitle: string;

  /** Hero Body */
  heroBody?: Document | undefined;

  /** Primary Navigation Items */
  primaryNavigationItems?: string[] | undefined;

  /** Metadata */
  metadata?: ISeo | undefined;

  /** Permalink Base */
  permalinkBase?: string | undefined;
}

/** Customize content that appears on Post listing pages */

export interface IPostListingSettings
  extends Entry<IPostListingSettingsFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "postListingSettings";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IQuoteFields {
  /** Internal Name */
  name?: string | undefined;

  /** Theme */
  theme?: "dark" | "light" | undefined;

  /** Text */
  text: Document;

  /** Citation */
  citation?: string | undefined;

  /** Citation Details */
  citationDescriptor?: string | undefined;

  /** Alignment */
  alignment?: "center" | "left" | undefined;

  /** Image */
  image?: Asset | undefined;

  /** Image Aspect Ratio */
  imageAspectRatio?: "auto" | "16-9" | "4-5" | "1-1" | undefined;
}

export interface IQuote extends Entry<IQuoteFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "quote";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IRedirectsFields {
  /** URL */
  url: string;

  /** Status Code */
  statusCode?: "301" | "302" | undefined;

  /** Target */
  target: string;
}

export interface IRedirects extends Entry<IRedirectsFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "redirects";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ISectionFields {
  /** Internal Name */
  name?: string | undefined;

  /** Modules */
  modules?:
    | (IAccordion | IHero | ILogoCloud | IMulticard | IPostList | IText)[]
    | undefined;

  /** Theme */
  theme?: "primary" | "secondary" | "default" | "inverse" | undefined;

  /** Flat Hierarchy */
  flatHierarchy?: boolean | undefined;
}

/** A wrapper module, for special colors and styles. */

export interface ISection extends Entry<ISectionFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "section";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ISectionNavFields {
  /** Internal Name */
  name?: string | undefined;

  /** Links */
  links?: ILink[] | undefined;

  /** Horizontal Layout */
  horizontalLayout?: boolean | undefined;
}

export interface ISectionNav extends Entry<ISectionNavFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "sectionNav";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ISeoFields {
  /** SEO Title */
  seoTitle?: string | undefined;

  /** SEO Description */
  seoDescription?: string | undefined;

  /** SEO Keywords */
  seoKeywords?: string[] | undefined;

  /** Canonical URL */
  canonicalUrl?: string | undefined;

  /** Social Title */
  socialTitle?: string | undefined;

  /** Social Description */
  socialDescription?: string | undefined;

  /** Social Image */
  socialImage?: Asset | undefined;

  /** Hide From Search Engines? */
  hideFromSearchEngines?: boolean | undefined;

  /** Authorization User */
  authUser?: string | undefined;

  /** Authorization Password */
  authPass?: string | undefined;
}

/** Metadata for SEO and social sharing */

export interface ISeo extends Entry<ISeoFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "seo";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ISettingsFields {
  /** Site Title */
  title: string;

  /** Legal Name */
  legalName?: string | undefined;

  /** Metadata */
  metadata?: ISeo | undefined;

  /** Logo Svg */
  logoSvg?: string | undefined;

  /** Logo Image */
  logoImage?: Asset | undefined;

  /** Image Quality */
  imagesQuality?: number | undefined;

  /** Main Navigation */
  mainNavigation?: (ILink | ISimpleList | INavItem)[] | undefined;

  /** Nav CTA 1 */
  navCta1?: ILink | undefined;

  /** Nav CTA 2 */
  navCta2?: ILink | undefined;

  /** Footer Navigation */
  footerNavigation?: (ILink | ISimpleList)[] | undefined;

  /** Legal Navigation */
  legalNavigation?: ILink[] | undefined;

  /** Facebook */
  facebook?: string | undefined;

  /** Twitter */
  twitter?: string | undefined;

  /** Instagram */
  instagram?: string | undefined;

  /** LinkedIn */
  linkedIn?: string | undefined;

  /** Pinterest */
  pinterest?: string | undefined;

  /** Google Analytics ID */
  googleAnalyticsId?: string | undefined;

  /** Google Tag Manager ID */
  googleTagManagerId?: string | undefined;

  /** CookieBot Id */
  cookieBotId?: string | undefined;

  /** Facebook App ID */
  facebookAppId?: string | undefined;

  /** Greenhouse Board ID */
  greenhouseBoardToken?: string | undefined;

  /** Marker.io Destination ID */
  markerIoDestinationId?: string | undefined;

  /** Marketo Hostname */
  marketoHostname?: string | undefined;

  /** Marketo Munchkin ID */
  marketoMunchkinId?: string | undefined;

  /** Enable Search */
  enableSearch?: boolean | undefined;
}

export interface ISettings extends Entry<ISettingsFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "settings";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ISimpleListFields {
  /** Internal Name */
  name?: string | undefined;

  /** Title */
  title?: string | undefined;

  /** Items */
  items?: ILink[] | undefined;
}

/** Specific to navigation. Used for sub-navigation list */

export interface ISimpleList extends Entry<ISimpleListFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "simpleList";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ITextFields {
  /** Internal Name */
  name?: string | undefined;

  /** Eyebrow */
  eyebrow?: string | undefined;

  /** Title */
  title?: string | undefined;

  /** Text */
  text?: Document | undefined;

  /** Text layout */
  textLayout?: "one column" | "two column" | undefined;
}

/** This is for the most basic of texts. A title and a body. It's used for accordion items and for anything else. */

export interface IText extends Entry<ITextFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "text";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IVideoFields {
  /** Internal Name */
  internalName?: string | undefined;

  /** Theme */
  theme?: "dark" | "light" | undefined;

  /** Headline */
  headline?: IHeadline | undefined;

  /** Section ID */
  sectionId?: string | undefined;

  /** Url */
  url?: string | undefined;

  /** Poster */
  poster?: Asset | undefined;

  /** Thumbnail */
  thumbnail?: Asset | undefined;

  /** Open in modal ? */
  openInModal?: boolean | undefined;

  /** Button placement */
  btnPosition?: "bottom left" | "center" | "bottom right" | undefined;
}

export interface IVideo extends Entry<IVideoFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "video";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export type CONTENT_TYPE =
  | "accordion"
  | "accordionItem"
  | "card"
  | "careersList"
  | "comparisonTable"
  | "ctaBanner"
  | "divider"
  | "feature"
  | "featureStack"
  | "footnote"
  | "form"
  | "headline"
  | "hero"
  | "heroCarousel"
  | "icon"
  | "image"
  | "inPageNav"
  | "link"
  | "list"
  | "listItem"
  | "logoCloud"
  | "marketoForm"
  | "multicard"
  | "navItem"
  | "page"
  | "pageSimple"
  | "panorama"
  | "person"
  | "post"
  | "postList"
  | "postListingSettings"
  | "quote"
  | "redirects"
  | "section"
  | "sectionNav"
  | "seo"
  | "settings"
  | "simpleList"
  | "text"
  | "video";

export type IEntry =
  | IAccordion
  | IAccordionItem
  | ICard
  | ICareersList
  | IComparisonTable
  | ICtaBanner
  | IDivider
  | IFeature
  | IFeatureStack
  | IFootnote
  | IForm
  | IHeadline
  | IHero
  | IHeroCarousel
  | IIcon
  | IImage
  | IInPageNav
  | ILink
  | IList
  | IListItem
  | ILogoCloud
  | IMarketoForm
  | IMulticard
  | INavItem
  | IPage
  | IPageSimple
  | IPanorama
  | IPerson
  | IPost
  | IPostList
  | IPostListingSettings
  | IQuote
  | IRedirects
  | ISection
  | ISectionNav
  | ISeo
  | ISettings
  | ISimpleList
  | IText
  | IVideo;

export type LOCALE_CODE = "en";

export type CONTENTFUL_DEFAULT_LOCALE_CODE = "en";
